---
generic-service:
  nameOverride: wmt-worker
  replicaCount: 1

  image:
    repository: quay.io/hmpps/wmt-worker
    tag: app_version    # override at deployment time
    port: 3000

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    WMT_DB_NAME: "hmpps_workload"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-workload:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    rds-instance-output:
      WMT_DB_USERNAME: "database_username"
      WMT_DB_PASSWORD: "database_password"
      WMT_DB_SERVER: "rds_instance_address"
    s3-bucket-output:
      AWS_ACCESS_KEY_ID: "access_key_id"
      AWS_SECRET_ACCESS_KEY: "secret_access_key"
      S3_BUCKET_NAME: "bucket_name"


generic-prometheus-alerts:
  targetApplication: wmt-worker
  alertSeverity: hmpps-tier
