---
generic-service:
  nameOverride: wmt-worker
  replicaCount: 1

  image:
    repository: quay.io/hmpps/wmt-worker
    tag: app_version    # override at deployment time
    port: 3000
  resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      memory: 2048Mi

  livenessProbe:
    httpGet:
      path: /liveness

  readinessProbe:
    httpGet:
      path: /liveness
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    PGSSLMODE: "no-verify"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-workload:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    rds-instance-output:
      WMT_DB_USERNAME: "database_username"
      WMT_DB_PASSWORD: "database_password"
      WMT_DB_SERVER: "rds_instance_address"
      WMT_DB_NAME: "database_name"
    s3-bucket-output:
      AWS_ACCESS_KEY_ID: "access_key_id"
      AWS_SECRET_ACCESS_KEY: "secret_access_key"
      S3_BUCKET_NAME: "bucket_name"


generic-prometheus-alerts:
  targetApplication: wmt-worker
  alertSeverity: hmpps-tier
