---
generic-service:
  nameOverride: wmt-worker
  replicaCount: 1
  poddisruptionbudget:
    enabled: false

  image:
    repository: quay.io/hmpps/wmt-worker
    tag: app_version    # override at deployment time
    port: 3000
  resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      memory: 4096Mi

  livenessProbe:
    httpGet:
      path: /liveness

  readinessProbe:
    httpGet:
      path: /liveness
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    PGSSLMODE: "no-verify"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    wmt-worker:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    rds-live-instance-output:
      WMT_DB_USERNAME: "database_username"
      WMT_DB_PASSWORD: "database_password"
      WMT_DB_SERVER: "rds_instance_address"
      WMT_DB_NAME: "database_name"
    s3-extract-bucket-output:
      ETL_S3_ACCESS_KEY_ID: "access_key_id"
      ETL_S3_SECRET_ACCESS_KEY: "secret_access_key"
      ETL_S3_BUCKET_NAME: "bucket_name"
    s3-dashboard-bucket-output:
      DASHBOARD_S3_ACCESS_KEY_ID: "access_key_id"
      DASHBOARD_S3_SECRET_ACCESS_KEY: "secret_access_key"
      WMT_DASHBOARD_BUCKET: "bucket_name"
    hmpps-reductions-completed-sqs-instance-output:
      ETL_SQS_ACCESS_KEY_ID: "access_key_id"
      ETL_SQS_SECRET_ACCESS_KEY: "secret_access_key"
      ETL_SQS_QUEUE_URL: "sqs_queue_url"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_ACCESS_KEY_ID: "access_key_id"
      AUDIT_SQS_SECRET_ACCESS_KEY: "secret_access_key"
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
    wmt-hmpps-domain-events-topic:
      STAFF_EVENT_SQS_ACCESS_KEY_ID: "access_key_id"
      STAFF_EVENT_SQS_SECRET_ACCESS_KEY: "secret_access_key"
      STAFF_EVENT_SNS_TOPIC_ARN: "topic_arn"


generic-prometheus-alerts:
  targetApplication: wmt-worker
  alertSeverity: hmpps-tier
