version: "3"
services:
    localstack:
        image: localstack/localstack:0.12.15
        networks:
          - hmpps
        container_name: hmpps-workload-localstack
        ports:
          - "4566:4566"
          - "4571:4571"
          - 8999:8080
        environment:
          - SERVICES=s3,sqs,sns
          - DEBUG=${DEBUG- }
          - DOCKER_HOST=unix:///var/run/docker.sock
          - DEFAULT_REGION=eu-west-2
        volumes:
          - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
          - "/var/run/docker.sock:/var/run/docker.sock"
          - $PWD/test/integration/resources:/docker-entrypoint-initaws.d
    hmpps-workload:
      image: quay.io/hmpps/hmpps-workload:latest
      networks:
        - hmpps
      container_name: hmpps-workload
      ports:
        - "8081:8080"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
      environment:
        - SERVER_PORT=8080
        - SPRING_PROFILES_ACTIVE=dev
        - DATABASE_ENDPOINT=postgres:5432
      entrypoint: ["/bin/sh", "-c" , "sleep 10 && java -javaagent:/app/agent.jar -jar /app/app.jar"]
      depends_on:
          - "postgres"
    postgres:
      image: postgres:11
      networks:
        - hmpps
      container_name: hmpps-workload-postgres
      restart: always
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_PASSWORD=dev
        - POSTGRES_USER=root
networks:
  hmpps: