
exports.up = function (knex, Promise) {
  return knex.schema.withSchema('staging').createTable('stg_wmt_extract', function (table) {
    table.increments('id')
    table.string('trust')
    table.string('region_desc')
    table.string('region_code')
    table.string('ldu_desc')
    table.string('ldu_code')
    table.string('team_desc')
    table.string('team_code')
    table.string('om_surname')
    table.string('om_Forename')
    table.string('om_grade_code')
    table.string('om_key')
    table.string('commtierd1a')
    table.string('commtierc1a')
    table.string('commtier0')
    table.string('commtierd2')
    table.string('commtier1a')
    table.string('commtier')
    table.string('commtierd1')
    table.string('commtierc2')
    table.string('commtier3a')
    table.string('commtierc1')
    table.string('commtierB2')
    table.string('commtierB1')
    table.string('commtierA')
    table.string('licensetier0')
    table.string('licensetierd2')
    table.string('licensetierd1')
    table.string('licensetierc2')
    table.string('licensetierc1')
    table.string('licensetierB2')
    table.string('licensetierB1')
    table.string('licensetierA')
    table.string('custtier0')
    table.string('custtierd2')
    table.string('custtierd1')
    table.string('custtierc2')
    table.string('custtierc1')
    table.string('custtierB2')
    table.string('custtierB1')
    table.string('custtierA')
    table.string('comIn1st16Weeks')
    table.string('licIn1st16Weeks')
    table.string('datestamp')
    table.string('vcrn_count')
  }).catch(function (error) {
    console.log(error)
    throw error
  })
}

exports.down = function (knex, Promise) {
  knex.schema.withSchema('staging').dropTable('stg_wmt_extract')
}
