version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.8
  slack: circleci/slack@4.4.2

parameters:
  alerts-slack-channel:
    type: string
    default: manage_a_workforce_dev
  node-version:
    type: string
    default: 14.17-browsers
  mssql_tag:
    default: "2019-CU11-ubuntu-20.04"
    type: string
  sa_password:
    default: "yourStrong(!)Password"
    type: string

jobs:
  build:
    executor:  
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.cache
      - run:
          command: |
            DATE=$(date '+%Y-%m-%d')
            export BUILD_NUMBER=${DATE}.${CIRCLE_BUILD_NUM}
            export GIT_REF="$CIRCLE_SHA1"
            npm run record-build-info
      - run: # Run linter after build because the integration test code depend on compiled typescript...
          name: Linter check
          command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build-info.json
            - build
            - dist

  unit_test:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: unit tests
          command: npm run test
      - slack/notify:
          event: fail
          channel: << pipeline.parameters.alerts-slack-channel >>
          template: basic_fail_1
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results/unit-test-reports.html

  integration_test:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
      - image: mcr.microsoft.com/mssql/server:<< pipeline.parameters.mssql_tag >>
        environment:
          - SA_PASSWORD=<< pipeline.parameters.sa_password >>
          - ACCEPT_EULA=y
          - DOCKER_HOST=unix:///var/run/docker.sock
          - TMPDIR=/private
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run:
          name: initialise database
          command: |
            docker pull quay.io/hmpps/hmpps-workload:latest
            docker run -d -e DATABASE_USERNAME=sa -e DATABASE_PASSWORD=<< pipeline.parameters.sa_password >> --network host --name hmpps-workload quay.io/hmpps/hmpps-workload
            docker exec hmpps-workload curl --retry 10 --retry-connrefused http://localhost:8080/health/readiness

      - run:
         name: Run integration tests
         command: npm run integration-test
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results/integration-test-reports.html

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
        filters:
          tags:
            ignore: /.*/
      - unit_test:
          context:
            - hmpps-common-vars
          requires:
            - build
      - integration_test:
          requires:
            - build
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - helm_lint
            - unit_test
            - integration_test
            - build_docker

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/npm_security_audit:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars