version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.4.0

jobs:
  build:
    executor:
      name: hmpps/node
      tag: 14.17-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
     