
exports.up = function (knex, Promise) {
  return knex.schema.withSchema('staging').createTable('wmt_extract', function (table) {
    table.increments('id')
    table.string('trust')
    table.string('region_desc')
    table.string('region_code')
    table.string('ldu_desc')
    table.string('ldu_code')
    table.string('team_desc')
    table.string('team_code')
    table.string('om_surname')
    table.string('om_forename')
    table.string('om_grade_code')
    table.string('om_key')
    table.string('commtierd1a')
    table.string('commtierc1a')
    table.string('commtier0')
    table.string('commtierd2')
    table.string('commtier1a')
    table.string('commtier')
    table.string('commtierd1')
    table.string('commtierc2')
    table.string('commtier3a')
    table.string('commtierc1')
    table.string('commtierb2')
    table.string('commtierb1')
    table.string('commtiera')
    table.string('licencetier0')
    table.string('licencetierd2')
    table.string('licencetierd1')
    table.string('licencetierc2')
    table.string('licencetierc1')
    table.string('licencetierb2')
    table.string('licencetierb1')
    table.string('licencetiera')
    table.string('custtier0')
    table.string('custtierd2')
    table.string('custtierd1')
    table.string('custtierc2')
    table.string('custtierc1')
    table.string('custtierb2')
    table.string('custtierb1')
    table.string('custtiera')
    table.string('comin1st16weeks')
    table.string('licin1st16weeks')
    table.string('datestamp')
    table.string('vcrn_count')
  }).catch(function (error) {
    console.log(error)
    throw error
  })
}

exports.down = function (knex, Promise) {
  return knex.schema.withSchema('staging').dropTable('wmt_extract')
}
