const logger = require('../../app/services/log')

exports.up = function (knex, Promise) {
  return knex.schema.withSchema('staging').createTable('omic_teams', function (table) {
    table.increments('id')
    table.string('trust')
    table.string('region_desc')
    table.string('region_code')
    table.string('ldu_desc')
    table.string('ldu_code')
    table.string('team_desc')
    table.string('team_code')
    table.string('om_surname')
    table.string('om_forename')
    table.string('om_grade_code')
    table.string('om_key')
    table.string('commtier0')
    table.string('licencetier0')
    table.string('custtier0')
    table.string('comin1st16weeks')
    table.string('licin1st16weeks')
    table.string('datestamp')
    table.string('vcrn_count')
    table.string('pdu_code')
    table.string('pdu_desc')
    table.string('commtierd0')
    table.string('commtierd1')
    table.string('commtierd2')
    table.string('commtierd3')
    table.string('commtierc0')
    table.string('commtierc1')
    table.string('commtierc2')
    table.string('commtierc3')
    table.string('commtierb0')
    table.string('commtierb1')
    table.string('commtierb2')
    table.string('commtierb3')
    table.string('commtiera0')
    table.string('commtiera1')
    table.string('commtiera2')
    table.string('commtiera3')
    table.string('licencetierd0')
    table.string('licencetierd1')
    table.string('licencetierd2')
    table.string('licencetierd3')
    table.string('licencetierc0')
    table.string('licencetierc1')
    table.string('licencetierc2')
    table.string('licencetierc3')
    table.string('licencetierb0')
    table.string('licencetierb1')
    table.string('licencetierb2')
    table.string('licencetierb3')
    table.string('licencetiera0')
    table.string('licencetiera1')
    table.string('licencetiera2')
    table.string('licencetiera3')
    table.string('custtierd0')
    table.string('custtierd1')
    table.string('custtierd2')
    table.string('custtierd3')
    table.string('custtierc0')
    table.string('custtierc1')
    table.string('custtierc2')
    table.string('custtierc3')
    table.string('custtierb0')
    table.string('custtierb1')
    table.string('custtierb2')
    table.string('custtierb3')
    table.string('custtiera0')
    table.string('custtiera1')
    table.string('custtiera2')
    table.string('custtiera3')
  }).catch(function (error) {
    logger.error(error)
    throw error
  })
}

exports.down = function (knex, Promise) {
  return knex.schema.withSchema('staging').dropTable('omic_teams')
}
