module.exports = {
  CALCULATE_WORKLOAD_POINTS: 'CALCULATE-WORKLOAD-POINTS',
  CREATE_WORKLOAD: 'CREATE-WORKLOAD',
  PROCESS_IMPORT: 'PROCESS-IMPORT',
  PROCESS_REDUCTIONS: 'PROCESS-REDUCTIONS',
  PROCESS_ADJUSTMENTS: 'PROCESS-ADJUSTMENTS',
  CREATE_COURT_REPORTS: 'CREATE-COURT-REPORTS',
  PROCESS_REDUCTIONS_COURT_REPORTERS: 'PROCESS-REDUCTIONS-COURT-REPORTERS',
  COURT_REPORTS_CALCULATION: 'COURT-REPORTS-CALCULATION',
  GENERATE_DASHBOARD: 'GENERATE-DASHBOARD',
  CREATE_OMIC_WORKLOAD: 'CREATE-OMIC-WORKLOAD',
  CALCULATE_OMIC_WORKLOAD_POINTS: 'CALCULATE-OMIC-WORKLOAD-POINTS',
  RECALCULATE_WORKLOAD_POINTS: 'RECALCULATE-WORKLOAD-POINTS',
  REFRESH_VIEWS: 'REFRESH-VIEWS',
  RECONCILE_WORKLOAD: 'RECONCILE-WORKLOAD'
}
