module.exports = {
  CALCULATE_WORKLOAD_POINTS: 'CALCULATE-WORKLOAD-POINTS',
  CREATE_WORKLOAD: 'CREATE-WORKLOAD',
  PROCESS_IMPORT: 'PROCESS-IMPORT',
  CREATE_WORKLOAD_REPORT: 'CREATE-WORKLOAD-REPORT'
}
