module.exports = {
  CALCULATE_WORKLOAD_POINTS: 'CALCULATE-WORKLOAD-POINTS',
  CREATE_WORKLOAD: 'CREATE-WORKLOAD',
  PROCESS_IMPORT: 'PROCESS-IMPORT',
  PROCESS_REDUCTIONS: 'PROCESS-REDUCTIONS',
  PROCESS_ADJUSTMENTS: 'PROCESS-ADJUSTMENTS',
  COURT_REPORTS_CALCULATIONS: 'COURT-REPORTS-CALCULATIONS'
}
