---
generic-service:
  env:
    NODE_ENV: "production"
    PGSSLMODE: "no-verify"
    EXTRACT_LISTENER_CRON: "*/5 * 29 10 *"

  HMPPS_SQS_USE_WEB_TOKEN: "true"

  namespace_secrets:
    s3-extract-bucket-output:
      ETL_S3_BUCKET_NAME: "bucket_name"
    s3-dashboard-bucket-output:
      WMT_DASHBOARD_BUCKET: "bucket_name"
    hmpps-reductions-completed-sqs-instance-output:
      ETL_SQS_QUEUE_URL: "sqs_queue_url"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
    wmt-hmpps-domain-events-topic:
      STAFF_EVENT_SNS_TOPIC_ARN: "topic_arn"

# Alert for business hours only - 7am to 6pm UTC (8am to 7pm BST) on week days (Monday to Friday)
generic-prometheus-alerts:
  businessHoursOnly: true